# Generated by Django 5.1.4 on 2025-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(unique=True)),
                ('player_1_id', models.IntegerField()),
                ('player_2_id', models.IntegerField()),
                ('player_1_score', models.IntegerField()),
                ('player_2_score', models.IntegerField()),
                ('winner_id', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('games_won', models.IntegerField(default=0)),
                ('games_lost', models.IntegerField(default=0)),
                ('points_scored', models.IntegerField(default=0)),
                ('points_conceded', models.IntegerField(default=0)),
                ('total_time_played', models.FloatField(default=0.0)),
            ],
        ),
    ]
