# Generated by Django 5.1.4 on 2025-02-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='win_ratio',
            field=models.FloatField(default=0.0),
        ),
    ]
