services:
  ai-opponent:
    container_name: ai-opponent
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - ":8000"
    volumes:
      - ..:/app
    env_file:
      - path: ./.env.example #TODO: change
        required: true
    environment:
      - DJANGO_SETTINGS_MODULE=AIOpponent.settings
    networks:
      - transcendence

networks:
  transcendence:
    external: true

