services:
  ai-opponent:
    container_name: ai-opponent
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8004:8000"
    volumes:
      - ..:/app
    environment:
      - DJANGO_SETTINGS_MODULE=AIOpponent.settings
    networks:
      - transcendence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  transcendence:
    external: true

