services:
  # ...other services...

  # Matchmaking service
  matchmaking:
    extends:
      file: ./matchmaking/docker/docker-compose.yml
      service: matchmaking
    networks:
      - transcendence

  matchmaking-postgres:
    extends:
      file: ./matchmaking/docker/docker-compose.yml
      service: matchmaking-postgres
    networks:
      - transcendence

  matchmaking-redis:
    extends:
      file: ./matchmaking/docker/docker-compose.yml
      service: matchmaking-redis
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge

volumes:
  matchmaking_postgres_data:
