services:
  #UAM service
  accounts:
    container_name: accounts
    extends:
      file: ./user-access-management/docker/docker-compose.yml
      service: accounts
    networks:
      - transcendence
      - accounts-internal
    restart: on-failure
    depends_on:
      - accounts-postgres
  
  accounts-postgres:
    extends:
      file: ./user-access-management/docker/docker-compose.yml
      service: accounts-postgres
    networks:
      - accounts-internal
    restart: on-failure

  # Frontend
  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend
    networks:
      - transcendence
    depends_on:
      - accounts
      - pong-api
      - matchmaking
      # - ai-messages
    restart: on-failure

  # pong-api service
  pong-api:
    extends:
      file: ./pong-api/docker/docker-compose.yml
      service: pong-api
    networks:
      - transcendence
    depends_on:
      - matchmaking
    restart: on-failure

  # AI Opponent
  ai-opponent:
    extends:
      file: ./ai-opponent/docker/docker-compose.yml
      service: ai-opponent
    networks:
      - transcendence
    depends_on:
      - matchmaking
      - pong-api
    restart: on-failure

  # game-history service
  game-history:
    extends:
      file: ./game-history/docker/docker-compose.yml
      service: game-history
    depends_on:
      - game-history-postgres
    networks:
      - transcendence
      - game-history-internal
    restart: on-failure

  game-history-postgres:
    extends:
      file: ./game-history/docker/docker-compose.yml
      service: game-history-postgres
    networks:
      - game-history-internal
    restart: on-failure

  # Matchmaking service
  matchmaking:
    extends:
      file: ./matchmaking/docker/docker-compose.yml
      service: matchmaking
    depends_on:
      - matchmaking-postgres
      - matchmaking-redis
      - game-history
    networks:
      - transcendence
      - matchmaking_internal
    restart: on-failure

  matchmaking-postgres:
    extends:
      file: ./matchmaking/docker/docker-compose.yml
      service: matchmaking-postgres
    networks:
      - matchmaking_internal
    restart: on-failure

  matchmaking-redis:
    extends:
      file: ./matchmaking/docker/docker-compose.yml
      service: matchmaking-redis
    networks:
      - matchmaking_internal
    restart: on-failure

  # AI messages service (DistilGPT2)
  # ai-messages:
  #   extends:
  #     file: ./ai_messages/docker/docker-compose.yml
  #     service: ai-messages
  #   networks:
  #     - transcendence
  #   restart: on-failure

  # AI messages service (Deepseek)
  # ai-messages-deepseek:
  #   extends:
  #     file: ./ai_messages_deepseek/docker/docker-compose.yml
  #     service: ai-messages-deepseek
  #   networks:
  #     - transcendence
  #   restart: on-failure
  #   volumes:
  #     - ai_messages_models:/app/models

networks:
  transcendence:
    driver: bridge
    name: transcendence
  matchmaking_internal:
    driver: bridge
    name: matchmaking_internal
  game-history-internal:
    driver: bridge
    name: game-history-internal
  accounts-internal:
    driver: bridge
    name: accounts-internal

volumes:
  matchmaking_postgres_data:
    driver: local
  game-history-postgres-data:
    driver: local
  # ai_messages_models:
  accounts-postgres_data:
    driver: local
