# Generated by Django 5.1 on 2024-11-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_y', models.IntegerField(default=150)),
                ('player2_y', models.IntegerField(default=150)),
                ('ball_x', models.IntegerField(default=400)),
                ('ball_y', models.IntegerField(default=200)),
                ('ball_dx', models.IntegerField(default=1)),
                ('ball_dy', models.IntegerField(default=1)),
            ],
        ),
    ]
