# Generated by Django 3.2.21 on 2025-01-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiplayer',
            name='position',
            field=models.IntegerField(default=160),
        ),
    ]
