# Generated by Django 5.1.4 on 2025-02-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_aiplayer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiplayer',
            name='position',
            field=models.FloatField(default=160),
        ),
    ]
