services:
  postgres:
    image: postgres:16.6
    environment:
      POSTGRES_DB: matchmaking_db
      POSTGRES_USER: deniz
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deniz -d matchmaking_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  matchmaking:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=matchmaking.settings
      - DATABASE_URL=postgres://deniz:your_password@postgres:5432/matchmaking_db
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ../:/app

volumes:
  postgres_data:
