services:
  matchmaking:
    container_name: "matchmaking"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - ":8000"
    depends_on:
      matchmaking-postgres:
        condition: service_healthy
      matchmaking-redis:
        condition: service_healthy
    env_file:
      - path: ./.env
        required: true
    volumes:
      - ../:/app
    networks:
      - transcendence
      - matchmaking_internal

  matchmaking-postgres:
    container_name: "matchmaking-postgres"
    image: postgres:16.6
    env_file:
      - path: ./.env
        required: true
    volumes:
      - matchmaking_postgres_data:/var/lib/postgresql/data
    networks:
      - matchmaking_internal

  matchmaking-redis:
    container_name: matchmaking-redis
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - matchmaking_internal

networks:
  transcendence:
    external: true
  matchmaking_internal:
    driver: bridge

volumes:
  matchmaking_postgres_data:
