services:
  database:
    container_name: data
    image: postgres:16.6
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: foo
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - database
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: bar
    restart: unless-stopped

  user-service:
    container_name: user-service
    build:
      context: ./user-management
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://admin:foo@database:5432/postgres
    volumes:
      - ./user-management:/app
    restart: always

volumes:
  postgres-data:
