# Generated by Django 5.0.9 on 2025-01-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitingRoom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
