# Generated by Django 5.0.9 on 2025-01-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitingRoom', '0002_alter_match_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='created_at',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
