# Generated by Django 5.0.9 on 2025-01-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitingRoom', '0002_match_end_time_match_player1_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('creator_id', models.BigIntegerField()),
                ('max_players', models.IntegerField(choices=[(4, '4 Players'), (6, '6 Players')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished')], db_index=True, default='pending', max_length=10)),
                ('players', models.JSONField(default=list)),
                ('winner_id', models.BigIntegerField(blank=True, null=True)),
                ('matches', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'waitingRoom_tournament',
            },
        ),
    ]
