# Generated by Django 5.0.9 on 2025-01-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitingRoom', '0003_tournament'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='waitingRoom_player__78ac49_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='waitingRoom_status_2f3266_idx',
        ),
        migrations.RemoveField(
            model_name='match',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='start_time',
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('finished', 'Finished')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='match',
            table='waitingRoom_match',
        ),
    ]
