# Generated by Django 5.0.9 on 2025-02-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitingRoom', '0007_match_end_time_match_player_1_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player_1_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
