# Generated by Django 5.0.9 on 2025-02-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitingRoom', '0008_alter_match_player_1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player_1_name',
            field=models.CharField(default='Player', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='player_2_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
