# Generated by Django 5.0.9 on 2025-02-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitingRoom', '0009_match_player_1_name_match_player_2_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='creator_name',
            field=models.CharField(default='Player', max_length=50),
        ),
    ]
