# Generated by Django 5.0.9 on 2025-02-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitingRoom', '0010_tournament_creator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='player_names',
            field=models.JSONField(default=dict),
        ),
    ]
