services:
  pong-api:
    container_name: pong-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # ports:
    #   - "8002:8000"
    volumes:
      - ..:/app
    environment:
      - DJANGO_SETTINGS_MODULE=pongApi.settings
      - PYTHONPATH=/app
    networks:
      - transcendence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  transcendence:
    external: true
