services:
  pong-api:
    container_name: pong-api
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - ":8000"
    volumes:
      - ..:/app
    environment:
      - DJANGO_SETTINGS_MODULE=pongApi.settings
      - PYTHONPATH=/app
    networks:
      - transcendence

networks:
  transcendence:
    external: true
