services:
  ai-messages-deepseek:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # ports:
    #   - "8008:8000"
    volumes:
      - ..:/app
    environment:
      - MODEL_PATH=/app/models/DeepSeek-R1-Distill-Qwen-1.5B
    networks:
      - transcendence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  transcendence:
    external: true
