services:
  accounts:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8007:8000"
    volumes:
      - ..:/app
    # environment:
    #   - DJANGO_SETTINGS_MODULE=accounts.settings
    #   - PYTHONPATH=/app
    networks:
      - transcendence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health/"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  transcendence:
    external: true
