# Generated by Django 5.1.4 on 2025-01-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.PositiveIntegerField(default=3)),
                ('is_game_running', models.BooleanField(default=False)),
                ('is_game_ended', models.BooleanField(default=False)),
                ('player_1_id', models.IntegerField(blank=True, null=True)),
                ('player_2_id', models.IntegerField(blank=True, null=True)),
                ('player_1_name', models.CharField(default='Player 1', max_length=100)),
                ('player_2_name', models.CharField(default='Player 2', max_length=100)),
                ('player_1_score', models.IntegerField(default=0)),
                ('player_2_score', models.IntegerField(default=0)),
                ('player_1_position', models.IntegerField(default=50)),
                ('player_2_position', models.IntegerField(default=50)),
                ('ball_x_position', models.IntegerField(default=400)),
                ('ball_y_position', models.IntegerField(default=200)),
                ('ball_x_direction', models.IntegerField(default=10)),
                ('ball_y_direction', models.IntegerField(default=10)),
            ],
        ),
    ]
