# Generated by Django 5.0.9 on 2024-12-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_gameplayer_gamestate_player_delete_gameboard_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamestate",
            name="ball_x_velocity",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="gamestate",
            name="ball_y_velocity",
            field=models.IntegerField(default=10),
        ),
    ]
