# Generated by Django 5.1.4 on 2025-01-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamestate_game_height_gamestate_game_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='paddle_offset',
        ),
    ]
