# Generated by Django 5.1.4 on 2025-01-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_gamestate_paddle_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='paddle_width',
            field=models.IntegerField(default=20),
        ),
    ]
