# Generated by Django 5.1.4 on 2025-01-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_gamestate_paddle_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='ball_x_direction',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='ball_x_position',
            field=models.IntegerField(default=290),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='ball_y_direction',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='ball_y_position',
            field=models.IntegerField(default=190),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='paddle_width',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player_1_position',
            field=models.IntegerField(default=160),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player_2_position',
            field=models.IntegerField(default=160),
        ),
    ]
