# Generated by Django 5.1.4 on 2025-01-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_gamestate_players_gamestate_player_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='player_2',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_1_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_1_name',
            field=models.CharField(default='Player 1', max_length=100),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_2_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_2_name',
            field=models.CharField(default='Player 2', max_length=100),
        ),
    ]
