# Generated by Django 5.1.4 on 2025-01-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gamestate_ball_x_direction_and_more'),
        ('game', '0004_alter_gamestate_paddle_width'),
    ]

    operations = [
    ]
