# Generated by Django 5.1.4 on 2025-01-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gamestate_ball_x_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='game_height',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='game_width',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='paddle_height',
            field=models.IntegerField(default=80),
        ),
    ]
