# Generated by Django 5.1.4 on 2025-01-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gamestate_game_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='paddle_width',
            field=models.IntegerField(default=30),
        ),
    ]
