# Generated by Django 5.1.4 on 2025-01-15 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_gamestate_player_1_remove_gamestate_player_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='player_1_id',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='player_2_id',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
