# Generated by Django 5.1.4 on 2025-01-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_merge_20250123_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='game_height',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='game_width',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='paddle_height',
            field=models.IntegerField(default=80),
        ),
    ]
