# Generated by Django 5.1.4 on 2025-01-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_gamestate_player_1_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='player_2',
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_1_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_2_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
