# Generated by Django 5.1.4 on 2025-01-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_gamestate_game_height_and_more'),
        ('game', '0006_alter_gamestate_game_height_and_more'),
    ]

    operations = [
    ]
