# Generated by Django 5.1.4 on 2025-01-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_gamestate_player_1_remove_gamestate_player_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='player_1_position',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_2_position',
            field=models.IntegerField(default=50),
        ),
    ]
