# Generated by Django 5.1.4 on 2025-01-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gamestate_ball_speed_alter_gamestate_ball_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='max_score',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
