# Generated by Django 5.1.4 on 2025-01-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gamestate_player_1_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='player_1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='player_2_score',
            field=models.IntegerField(default=0),
        ),
    ]
