# Generated by Django 5.1.4 on 2025-01-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_gamestate_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='paddle_width',
            field=models.IntegerField(default=15),
        ),
    ]
