# Generated by Django 5.1.4 on 2025-02-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_merge_20250127_1659'),
        ('game', '0010_alter_gamestate_paddle_width'),
    ]

    operations = [
    ]
