# Generated by Django 5.1.4 on 2025-02-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_merge_20250203_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='paddle_width',
            field=models.IntegerField(default=15),
        ),
    ]
