# Generated by Django 5.1.4 on 2025-02-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_gamestate_paddle_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='ball_radius',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='ball_speed',
            field=models.FloatField(default=1.2),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='ball_x_direction',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='ball_x_position',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='ball_y_direction',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='ball_y_position',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='game_height',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='game_width',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='move_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='paddle_height',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='paddle_offset',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='paddle_width',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player_1_position',
            field=models.FloatField(default=16),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player_2_position',
            field=models.FloatField(default=16),
        ),
    ]
