# Generated by Django 5.1.4 on 2025-02-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_gamestate_player_1_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='move_step',
            field=models.IntegerField(default=0.8),
        ),
    ]
