# Generated by Django 5.1.4 on 2025-02-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_gamestate_paddle_offset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='player_1_position',
            field=models.FloatField(default=17.5),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='player_2_position',
            field=models.FloatField(default=17.5),
        ),
    ]
