# Generated by Django 5.1.4 on 2025-02-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_gamestate_player_1_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='move_step',
            field=models.FloatField(default=0.5),
        ),
    ]
