# Generated by Django 5.1.4 on 2025-02-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_gamestate_move_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='ball_radius',
            field=models.FloatField(default=0.5),
        ),
    ]
