# Generated by Django 5.1.5 on 2025-01-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar_url",
            field=models.ImageField(
                blank=True,
                default="avatars/default.png",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
